---

- name: Install nginx
  apt:
   pkg: "{{ item }}"
   state: installed
   update_cache: yes
   cache_valid_time: 3600
  with_items:
   - "{% if 'passenger' in packages %}nginx-extras{% else %}nginx{% endif %}"

- { include: runit.yml, runit_scripts: [ "nginx", "nginx-log-forwarder" ], when: container }
