---

- name: Install Redis
  apt:
   pkg: "{{ item }}"
   state: installed
   update_cache: yes
   cache_valid_time: 3600
  with_items:
   - redis-server 
   - libhiredis-dev

- { include: runit.yml, runit_scripts: [ "redis" ], when: container }
